# Test workflow
name: Tests
on: push
jobs:
    test_job:
        name: Test Job
        runs-on: ubuntu-latest
        steps:
            - name: Setup workspace
              uses: dynod/repo-checkout@1.2.0
              with:
                  url: https://github.com/dynod/workspace.git
                  group: core
                  env: OUTPUT_ROOT=/github/workspace/out
            - name: Build python distribution
              uses: dynod/call-make@1.2.0
              with:
                  target: build
                  env: OUTPUT_ROOT=/github/workspace/out
            - name: Archive Python distribution
              uses: actions/upload-artifact@v1
              with:
                  name: dist
                  path: out/artifacts/python
            - name: Archive flake8 report
              uses: actions/upload-artifact@v1
              with:
                  name: flake8 report
                  path: out/flake-report
